package com.example.compose
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF824C76)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD7F1)
val onPrimaryContainerLight = Color(0xFF35082F)
val secondaryLight = Color(0xFF6F5867)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF9DAED)
val onSecondaryContainerLight = Color(0xFF271623)
val tertiaryLight = Color(0xFF815342)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCF)
val onTertiaryContainerLight = Color(0xFF321206)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight =  Color(0xFFFFFAFA)
val onBackgroundLight = Color(0xFF201A1E)
val surfaceLight = Color(0xFFFFF6F6)
 val onSurfaceLight = Color(0xFF201A1E)
val surfaceVariantLight = Color(0xFFFFFFFF)
val onSurfaceVariantLight = Color(0xFF4F444A)
val outlineLight = Color(0xFF80747B)
val outlineVariantLight = Color(0xFFD2C2CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362E33)
val inverseOnSurfaceLight = Color(0xFFFBEDF3)
val inversePrimaryLight = Color(0xFFF5B2E2)

val primaryDark = Color(0xFFF5B2E2)
val onPrimaryDark = Color(0xFF4E1E45)
val primaryContainerDark = Color(0xFF68355D)
val onPrimaryContainerDark = Color(0xFFFFD7F1)
val secondaryDark = Color(0xFFDCBED1)
val onSecondaryDark = Color(0xFF3E2A38)
val secondaryContainerDark = Color(0xFF56404F)
val onSecondaryContainerDark = Color(0xFFF9DAED)
val tertiaryDark = Color(0xFFF5B9A3)
val onTertiaryDark = Color(0xFF4C2618)
val tertiaryContainerDark = Color(0xFF663C2C)
val onTertiaryContainerDark = Color(0xFFFFDBCF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFECDFE5)
val surfaceDark = Color(0xFF181216)
val onSurfaceDark = Color(0xFFECDFE5)
val surfaceVariantDark = Color(0xFF4F444A)
val onSurfaceVariantDark = Color(0xFFD2C2CA)
val outlineDark = Color(0xFF9B8D95)
val outlineVariantDark = Color(0xFF4F444A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFECDFE5)
val inverseOnSurfaceDark = Color(0xFF362E33)
val inversePrimaryDark = Color(0xFF824C76)



